export type MemoryNodeKind = "stimulus" | "concept" | "event" | "self" | "behavior";

export interface MemoryNode {
  id: string;
  label: string;
  strength: number;
  kind: MemoryNodeKind;
  /** Optional descriptive text about the memory */
  description?: string;
  /** ISO timestamp of the last time this memory was updated */
  timestamp?: string;
  /** Optional tags used to group memories */
  tags?: string[];
  /** Marks the node as a major milestone regardless of its kind */
  milestone?: boolean;
  /** The origin or modality that produced this memory */
  source?: string;
  /** Confidence score reported by the runtime */
  confidence?: number;
  /** Semantic meaning or interpretation of the memory */
  meaning?: string;
  /** Logical grouping/category for UI filtering */
  category?: string;
  /** Importance weight in range 0-1 */
  importance?: number;
  /** Sentiment or valence label */
  valence?: string;
  /** ISO timestamp when the node was created */
  createdAt?: string;
  /** ISO timestamp when the node was last updated */
  updatedAt?: string;
  /** ISO timestamp when the node was last accessed */
  lastAccessed?: string;
  /** Additional metadata generated by the runtime */
  metadata?: Record<string, unknown> | null;
}

export interface MemoryEdge {
  id: string;
  from: string;
  to: string;
  weight: number;
  /** Additional context about why the edge exists */
  context?: string;
  /** Parsed context payload */
  contextData?: Record<string, unknown> | null;
  /** Relationship label (identity_behavior, trigger, etc.) */
  relationship?: string;
  /** When the association was last strengthened */
  lastStrengthChange?: string;
}
