export type MemoryNodeKind = "stimulus" | "concept" | "event" | "self" | "behavior";

export interface MemoryNode {
  id: string;
  label: string;
  strength: number;
  kind: MemoryNodeKind;
  /** Optional descriptive text about the memory */
  description?: string;
  /** ISO timestamp of the last time this memory was updated */
  timestamp?: string;
  /** Optional tags used to group memories */
  tags?: string[];
  /** Marks the node as a major milestone regardless of its kind */
  milestone?: boolean;
  /** The origin or modality that produced this memory */
  source?: string;
  /** Confidence score reported by the runtime */
  confidence?: number;
  /** Semantic meaning or interpretation of the memory */
  meaning?: string;
  /** Logical grouping/category for UI filtering */
  category?: string;
  /** Importance weight in range 0-1 */
  importance?: number;
  /** Sentiment or valence label */
  valence?: string;
  /** ISO timestamp when the node was created */
  createdAt?: string;
  /** ISO timestamp when the node was last updated */
  updatedAt?: string;
  /** ISO timestamp when the node was last accessed */
  lastAccessed?: string;
  /** Additional metadata generated by the runtime */
  metadata?: Record<string, unknown> | null;
}

export interface MemoryEdge {
  id: string;
  from: string;
  to: string;
  weight: number;
  /** Additional context about why the edge exists */
  context?: string;
  /** Parsed context payload */
  contextData?: Record<string, unknown> | null;
  /** Relationship label (identity_behavior, trigger, etc.) */
  relationship?: string;
  /** When the association was last strengthened */
  lastStrengthChange?: string;
}

// Enhanced memory types for entity and timeline tracking
export type EntityType = "person" | "place" | "object" | "preference";

export interface Entity {
  id: string;
  entity_type: EntityType;
  name: string;
  description?: string;
  properties: Record<string, unknown>;
  first_seen: string; // ISO timestamp
  last_seen: string; // ISO timestamp
  occurrence_count: number;
  importance: number; // 0-1
  similarity?: number; // For search results
}

export type EventType = "discovery" | "reinforcement" | "update" | "forget";

export interface TimelineEvent {
  id: string;
  entity_id: string;
  entity_name: string;
  entity_type: EntityType;
  event_type: EventType;
  description: string;
  metadata: Record<string, unknown>;
  timestamp: string; // ISO timestamp
}

export interface SemanticSearchResult {
  node_id: string;
  text: string;
  label: string;
  description?: string;
  kind?: string;
  timestamp?: string;
  importance?: number;
  similarity: number;
}
